### ISSUE TITLE
Possibility of arrays deserialization in query string parameters

### ISSUE THREAD

**Issue by foliveiratdsis** [tdsis/lambda-forest#1]
AWS API Gateway supports some parameters types when using integration proxy, such as: body, resource, httpMethod, resource, queryStringParameters, etc (You can see HttpRequest.java class in the Lambda Forest project for more details).

Query string parameters are compose by a map of key and value.
`private Map<String, String> queryStringParameters;`

Today, the project does not have a pattern of query string parameters deserialization for arrays. Example:

I need to inform an array parameter of type query string parameter:
```
{
	"name": "test",
	"ids": "0cb650cd-6ad5-4513-b159-6ef56d547a17,2a90204c-1338-47b0-9207-14007b81dd84"
}
```
the field "ids" is a String splitted by comma (,)  or I could inform a JSON as String (for example).

This request above will be processed in my client application, the developer will have to do a split in the "ids" and put it in the string array.

The result of deserialization in my client application is as follows:
```
{
	"name": "test",
	"ids": [
                 "0cb650cd-6ad5-4513-b159-6ef56d547a17", 
                 "2a90204c-1338-47b0-9207-14007b81dd84"
         ]
}
```
The questions specified in this issue are:

- Is it possible to define a pattern of array deserialization in Lambda Forest project or a deserialization only can be done in the client application?
- What's the pattern can be define?
- The parse, convert or split is a hard work for developer?

**Comment by tommelo** [comment]
Hey @foliveiratdsis 

I'm not sure if it's worth it to implement an array deserializer based on a query string. In that case we would have to handle many scenarios like:

?param=1,2,3
?param=[1,2,3]
?param={[1,2,3]}

I think there's not much effort in converting the query parameter into an array with the current implementation.
E.g.:
```java
String parameter = getQuerystringParameter("myArray").get();
String [] list = parameter.split(",");
```
Let me know your thoughts if you still thinking it's worth to implement, otherwise this issue should be closed.

**Comment by fssantana** [comment]
I believe the AbstractRequestHandler derived classes could treat that as desired.

**Comment by tommelo** [comment]
@fssantana yep! Let's close this issue.

**Comment by fssantana** [comment]
Closing issue
