### ISSUE TITLE
Missing HTTP Status Codes in Http Exceptions

### ISSUE THREAD

**Issue by tommelo** [tdsis/lambda-forest#10]
The current implementation only supports the following HTTP Status when throwing HTTP Exceptions:

- 400 Bad Request
- 409 Conflict
- 500 Internal Server Error
- 405 Method Not Allowed
- 404 Not Found
- 401 Unauthorized
- 422 Unprocessable Entity

There's a variety of HTTP Status codes that should be supported: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status

**Comment by fssantana** [comment]
HTTP 4xx and 5xx Exceptions created based on https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status.
Available in version 1.0.0

**Comment by tommelo** [comment]
@fssantana Just a little detail that I noticed, the javadoc in all the implemented exception classes is describing the status code as "**method not allowed http response**".
